sonar.projectKey=sohila12_app-platform
sonar.organization=sohila12
sonar.sources=src
sonar.exclusions=**/.github/**,**/k8s/**,**/infra/**,**/argocd/**,**/docker-compose.yml,**/Dockerfile,**/README.md
