sonar.organization=${SONAR_ORG}
sonar.projectKey=${SONAR_PROJECT_KEY}
sonar.projectName=app-platform

sonar.sources=Application-Code/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

sonar.javascript.lcov.reportPaths=Application-Code/coverage/lcov.info
