
on:
  push:
    branches: [ "main", "test/ci-flow" ]
    paths:
      - "src/backend/**"
  pull_request:
    paths:
      - "src/backend/**"

jobs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

        with:
          projectBaseDir: src/backend
        env:
