resources:
  - ../../base

namePrefix: dev-

commonLabels:
  env: dev

images:
  - name: frontend
    newName: frontend
    newTag: dev-local
  - name: backend
    newName: backend
    newTag: dev-local

patchesStrategicMerge:
  - backend-service-selector-patch.yaml
