resources:
  - ../../base
namePrefix: dev-

images:
  - name: frontend
    newName: frontend
    newTag: dev-local
  - name: backend
    newName: backend
    newTag: dev-local

commonLabels:
  env: dev

patchesStrategicMerge:
  - backend-service-selector-patch.yaml
